Add `loading()` method to `Img` tag
yiisoft/html pull request #139
Opened 2022-10-23 17:19 UTC by jacobbudin

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  | #138

2022-10-24 06:36 UTC, vjik requested changes
Looks good 👍
Can you add line to changelog?

2022-10-24 22:57 UTC, jacobbudin commented
> Can you add line to changelog?

@vjik Yes. Done.

2022-10-25 07:00 UTC, vjik approved these changes

2022-10-25 07:00 UTC, vjik commented on CHANGELOG.md
> +- Chg #139: Add `loading()` method to `Img` tag (@jacobbudin)
```suggestion
- New #139: Add `loading()` method to `Img` tag (@jacobbudin)
```

2022-10-25 07:08 UTC, merged

2022-10-25 07:08 UTC, vjik commented
Thank you 👍