Add $attributes parameter to Html::img()
yiisoft/html pull request #148
Opened 2022-12-08 14:14 UTC by alien-art

2022-12-08 15:43 UTC, samdark approved these changes

2022-12-09 13:28 UTC, vjik requested changes

2022-12-09 13:28 UTC, vjik commented on CHANGELOG.md
> +- new #137: Add $attributes parameter to Html::img()
```suggestion
- New #137: Add `$attributes` parameter to `Html::img()` (@alien-art)
```

2022-12-09 13:28 UTC, vjik commented on CHANGELOG.md
>  ## 3.0.1 under development
```suggestion
## 3.1.0 under development
```

2022-12-09 13:28 UTC, vjik commented on src/Html.php
> +    public static function img(?string $url = null, ?string $alt = '',  array $attributes = []): Img
@alien-art Can you add tests?

2022-12-12 09:05 UTC, alien-art commented on src/Html.php
> +    public static function img(?string $url = null, ?string $alt = '',  array $attributes = []): Img
added test

2022-12-12 09:14 UTC, merged