Add class for <hr> tag #191
yiisoft/html pull request #192
Opened 2024-03-28 15:50 UTC by abdulmannans

| Q             | A
| ------------- | ---
| New feature?  | ✔️
| Fixed issues | #191 

Test cases Passed

2024-03-28 16:17 UTC, vjik requested changes
Can you add method to Html helper class and info to readme?

2024-03-28 16:36 UTC, abdulmannans commented
@vjik Please check and let me know

2024-03-30 23:18 UTC, abdulmannans commented
@vjik can you please review this?

2024-03-31 09:41 UTC, vjik requested changes
Just a little bit left. See suggestions and add line to changelog.

2024-03-31 09:41 UTC, vjik commented on src/Html.php
> +    public static function hr(): Hr
```suggestion
    public static function hr(array $attributes = []): Hr
```

2024-03-31 09:41 UTC, vjik commented on src/Html.php
> +    public static function hr(): Hr
Add tests for this method

2024-04-05 13:18 UTC, vjik requested changes

2024-04-09 17:50 UTC, vjik approved these changes

2024-04-09 17:52 UTC, merged

2024-04-09 17:52 UTC, vjik commented
@abdulmannans Thank you!